apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app.name}}-clusterip
spec:
  selector:
    link_converter: {{.Values.app.link_converter}}
  ports:
  - port: {{.Values.app.port}}
    protocol: TCP