apiVersion: v1
kind: Service
metadata:
  name: {{.Values.api.name}}-clusterip
spec:
  selector:
    link_converter: {{.Values.api.link_converter}}
  ports:
  - port: {{.Values.api.port}}
    protocol: TCP