apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rabbitmq.name }}-clusterip
spec:
  selector:
    link_converter: {{ .Values.rabbitmq.link_converter }}
  ports:
  - port: {{ .Values.rabbitmq.ports.amqp_port }}
    protocol: TCP
  - port: {{ .Values.rabbitmq.ports.management_port }}
    protocol: TCP